name: Publish Package to npmjs

on:
  push:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun i
      - run: bun run dist

      - name: Publish to NPM
        if: github.event_name == 'release'
        working-directory: dist
        run: |
          VERSION=$(node -p "JSON.parse(require('node:fs').readFileSync('package.json', 'utf8')).version")
          echo "Publishing version $VERSION"

          if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+- ]]; then
            npm publish --tag next
          else
            npm publish
          fi
